concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: Merge Request Checks
on:
  pull_request: {}
  workflow_dispatch:
permissions:
  actions: write
  contents: read
env:
  NODE_VERSION: 18.15.0

jobs:
  test:
    name: 🔬 Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g yarn
      - name: Setup node-api-dotnet dependency
        run: |
          git clone https://github.com/rijulg/node-api-dotnet.git
          cd node-api-dotnet
          git checkout patch-1
          dotnet build
          dotnet pack
          sudo cp -R out/pkg /var/lib/node-api-dotnet
          sudo chown -R 1001:123 /var/lib/node-api-dotnet
          lib_path=/usr/lib/$(uname -m)-linux-gnu
          sudo ln -s $lib_path/libdl.so.2 $lib_path/libdl.so
      - name: Setup hello dll
        run: dotnet build
        working-directory: dotnet
      - run: yarn install
      - name: Test
        run: |
          export DLL_PATH=$(pwd)/dotnet/bin/Debug/net6.0/dotnet.dll
          yarn test
